entrypoint: "gunicorn -b :$PORT main:app --timeout 1000"
env: flex
runtime: python
runtime_config:
  python_version: 3
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 4
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.9
  target_concurrent_requests: 100
resources:
  cpu: 2
  memory_gb: 2
